[package]
name = "crop"
version = "1.0.0"
edition = "2021"

authors = ["Kendrick Gr√ºnberg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
image = "0.23.14"
